# noctalia: Wayland desktop shell panel (window switcher, launcher, clipboard).
{ config, lib, pkgs, inputs, ... }:
let
  user = config.home.userName;
in
{
  imports = [
    inputs.noctalia.nixosModules.default
  ];

  programs.noctalia = {
    enable = true;
    # recommendedServices enables NetworkManager, Bluetooth, UPower, and a
    # power profile service. On WSL hosts these are both useless (WSL2 does
    # not expose Wi-Fi/Bluetooth hardware to Linux) and harmful:
    #
    #   recommendedServices.enable = true
    #     -> noctalia module sets networking.networkmanager.enable = true
    #     -> nixpkgs networkmanager module (networkmanager.nix) also sets
    #        networking.wireless.enable = true to run wpa_supplicant over D-Bus
    #     -> the networking.wireless module generates wpa_supplicant.service
    #        with a hardcoded BindPaths=/dev/rfkill (plus DeviceAllow=/dev/rfkill)
    #        inside a PrivateDevices sandbox
    #     -> /dev/rfkill does not exist in WSL (no radio hardware), so systemd
    #        fails to set up the mount namespace: status 226/NAMESPACE
    #     -> wpa_supplicant.service fails and `nixos-rebuild switch` exits 4
    #
    # Hence: only enable these services on non-WSL hosts.
    # `config.wsl.enable or false` also keeps hosts that never import the
    # nixos-wsl module (e.g. pro830) from failing to evaluate.
    recommendedServices.enable = !(config.wsl.enable or false);
  };

  home-manager.users.${user} =
    { ... }:
    {
      # Point the wallpaper panel at nixos-artwork wallpapers.
      xdg.configFile."noctalia/config.toml".text = ''
        # Generated by home-manager; the store path is refreshed on every rebuild.

        # Community plugin: daily Bing/NASA wallpaper (auto-clones the official +
        # community plugin sources since no [[plugins.source]] is declared).
        [plugins]
        enabled = [ "nzlov/daily-wallpaper" ]

        [plugin_settings."nzlov/daily-wallpaper"]
        source = "bing"

        [shell]
        polkit_agent = true
      '';

      # Niri binds that talk to noctalia.
      programs.niri.settings = {
        spawn-at-startup = [
          {
            argv = [
              "noctalia"
            ];
          }
        ];

        binds = {
          "Mod+D" = {
            hotkey-overlay = {
              title = "Open Noctalia Launcher";
            };
            action.spawn = [ "noctalia" "msg" "panel-toggle" "launcher" ];
          };
          # Mod+Alt+L locks the screen via noctalia.
          "Mod+Alt+L" = {
            hotkey-overlay = { title = "Lock the Screen"; };
            action.spawn = [ "noctalia" "msg" "session" "lock" ];
          };

          # Open the Noctalia clipboard panel.
          "Mod+V".action.spawn = [ "noctalia" "msg" "panel-toggle" "clipboard" ];
        };
      };
    };
}
