# noctalia: point the wallpaper panel at nixos-artwork wallpapers.
{ config, lib, pkgs, ... }:
{
  xdg.configFile."noctalia/config.toml".text = ''
    # Generated by home-manager; the store path is refreshed on every rebuild.

    # Community plugin: daily Bing/NASA wallpaper (auto-clones the official +
    # community plugin sources since no [[plugins.source]] is declared).
    [plugins]
    enabled = [ "nzlov/daily-wallpaper" ]

    [plugin_settings."nzlov/daily-wallpaper"]
    source = "bing"

    [shell]
    polkit_agent = true
  '';
}
